# Generated by Django 4.2.27 on 2026-02-14 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CPAUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('license_number', models.CharField(help_text='CPA License Number', max_length=50)),
                ('license_state', models.CharField(help_text='State (e.g., NY)', max_length=2)),
                ('is_verified', models.BooleanField(default=False)),
                ('stripe_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('integration_type', models.CharField(default='API', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cpa_payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client_bonus_summary', models.CharField(default='', help_text="e.g., '$300 Cash Bonus'", max_length=255)),
                ('client_requirements', models.TextField(default='', help_text="e.g., 'Must deposit $15k within 30 days.'")),
                ('application_link', models.URLField(blank=True, help_text="The direct link to the bank's application page.", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('terms_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayoutBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PROCESSING', 'Processing'), ('PAID', 'Paid')], default='OPEN', max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('reference_note', models.CharField(help_text='e.g. January 2026 Payouts', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_cpa_payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agreed_platform_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONVERTED', 'Converted'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('gen_date', models.DateTimeField(auto_now_add=True)),
                ('conversion_date', models.DateTimeField(blank=True, null=True)),
                ('cpa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='api.cpauser')),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.offer')),
                ('payout_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='api.payoutbatch')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee_type', models.CharField(choices=[('CPA', 'CPA User'), ('AGORA', 'Agora Platform'), ('CLIENT', 'End Client')], max_length=20)),
                ('payee_reference_id', models.IntegerField(help_text='ID of the CPA or System')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('ACH', 'ACH Transfer'), ('WIRE', 'Wire Transfer'), ('CHECK', 'Check'), ('INTERNAL', 'Internal Adjustment')], max_length=20)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='PROCESSING', max_length=50)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.referral')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.financialcompany')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='api.product'),
        ),
    ]
