# Generated by Django 4.2.27 on 2026-02-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Display this offer on the storefront'),
        ),
    ]
