# Generated by Django 4.2.27 on 2026-02-13 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cpauser_stripe_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PROCESSING', 'Processing'), ('PAID', 'Paid')], default='OPEN', max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('reference_note', models.CharField(help_text='e.g. January 2026 Payouts', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='referral',
            name='payout_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='api.payoutbatch'),
        ),
    ]
