# Generated by Django 4.2.27 on 2026-03-01 05:58

from django.db import migrations


def populate_categories(apps, schema_editor):
    ProductCategory = apps.get_model('api', 'ProductCategory')
    categories = [
        "Traditional IRA", "Roth IRA", "SEP IRA", "SIMPLE IRA",
        "Rollover IRA", "Self-Directed IRA", "Traditional 401k",
        "Roth 401k", "SIMPLE 401k", "Solo 401k", "Health Savings Account",
        "529 Education Savings Plans", "Coverdell education savings account",
        "Business Checking", "Business Credit Cards", "Crypto Tax Software",
        "Donor Advised Funds", "High-Yield Savings Accounts",
        "Certificate of Deposit", "Cash Sweep Accounts/Treasury Funds",
        "Small Business Loans", "Estate Planning/Trusts"
    ]
    for cat in categories:
        ProductCategory.objects.get_or_create(name=cat)

def remove_categories(apps, schema_editor):
    ProductCategory = apps.get_model('api', 'ProductCategory')
    ProductCategory.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_productcategory_alter_product_category'),
    ]

    operations = [
        migrations.RunPython(populate_categories, remove_categories),
    ]

