# Generated by Django 4.2.27 on 2026-02-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_payoutbatch_referral_payout_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='application_link',
            field=models.URLField(blank=True, help_text="The direct link to the bank's application page.", null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='client_bonus_summary',
            field=models.CharField(default='', help_text="e.g., '$300 Cash Bonus'", max_length=255),
        ),
        migrations.AddField(
            model_name='offer',
            name='client_requirements',
            field=models.TextField(default='', help_text="e.g., 'Must deposit $15k within 30 days.'"),
        ),
    ]
