# Generated by Django 4.2.27 on 2026-03-01 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20260301_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpauser',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='cpauser',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='cpauser',
            name='license_state',
        ),
        migrations.CreateModel(
            name='CPALicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(help_text='State (e.g., NY)', max_length=2)),
                ('license_number', models.CharField(help_text='CPA License Number', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cpa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='api.cpauser')),
            ],
        ),
    ]
