# Generated by Django 4.2.27 on 2026-03-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_cpauser_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='client_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Business', 'Business')], default='Individual', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('name', 'client_type')},
        ),
    ]
