# Generated by Django 4.2.27 on 2026-03-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_productcategory_client_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='client_state',
            field=models.CharField(blank=True, help_text='Used primarily for PWM', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Generated for specific products like PWM', max_length=50, null=True),
        ),
    ]
