# Generated by Django 4.2.27 on 2026-03-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_referral_client_state_referral_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='requires_client_state',
            field=models.BooleanField(default=False, help_text='If checked, creating a referral for this offer routes the CPA to a State Selection page.'),
        ),
    ]
