# Generated by Django 4.2.27 on 2026-04-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_offer_requires_client_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Optional contact email provided to the CPA upon referral generation.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Optional contact phone provided to the CPA upon referral generation.', max_length=20, null=True),
        ),
    ]
