# Generated by Django 4.2.27 on 2026-05-22 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_offer_contact_email_offer_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_users', to='api.financialcompany')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
