# Generated by Django 4.2.27 on 2026-05-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_financialuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='client_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
