# Generated by Django 4.2.27 on 2026-05-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_referral_client_name_referral_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='financial_pro_status',
            field=models.CharField(choices=[('NOT_VIEWED', 'Not Viewed'), ('VIEWED', 'Viewed'), ('CLIENT_CONTACTED', 'Client Contacted')], default='NOT_VIEWED', max_length=50),
        ),
    ]
