# Generated by Django 4.2.27 on 2026-05-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_referral_financial_pro_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='professional_name',
            field=models.CharField(blank=True, help_text='Optional name of the financial/legal professional.', max_length=255, null=True),
        ),
    ]
