# Generated by Django 4.2.27 on 2026-05-27 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_offer_professional_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('integration_type', models.CharField(default='API', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.financialcompany'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='cpa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='api.cpauser'),
        ),
        migrations.CreateModel(
            name='LegalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_users', to='api.legalcompany')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LegalLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(help_text='State registered (e.g., NY)', max_length=2)),
                ('bar_number', models.CharField(help_text='Bar Number', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Bar Number active status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='api.legaluser')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='legal_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.legalcompany'),
        ),
        migrations.AddField(
            model_name='referral',
            name='legal_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='made_referrals', to='api.legaluser'),
        ),
    ]
