# Generated by Django 4.2.27 on 2026-05-27 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_legalcompany_alter_product_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='financial_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='made_referrals', to='api.financialuser'),
        ),
    ]
