# Generated by Django 4.2.27 on 2026-05-27 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_referral_financial_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(help_text='State registered (e.g., NY)', max_length=2)),
                ('crd_number', models.CharField(help_text='CRD Number', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='CRD active status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('financial_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='api.financialuser')),
            ],
        ),
    ]
