# Generated by Django 4.2.27 on 2026-07-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_financiallicense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legallicense',
            name='legal_user',
        ),
        migrations.RemoveField(
            model_name='legaluser',
            name='company',
        ),
        migrations.RemoveField(
            model_name='legaluser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='legal_company',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='legal_user',
        ),
        migrations.AddField(
            model_name='financiallicense',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='LegalCompany',
        ),
        migrations.DeleteModel(
            name='LegalLicense',
        ),
        migrations.DeleteModel(
            name='LegalUser',
        ),
    ]
