# Generated by Django 4.2.27 on 2026-07-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_legallicense_legal_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financiallicense',
            name='firm_crd',
            field=models.CharField(blank=True, help_text='Firm CRD/SEC Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='financiallicense',
            name='zip_code',
            field=models.CharField(blank=True, help_text='ZIP Code', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='financiallicense',
            name='crd_number',
            field=models.CharField(help_text='Individual CRD Number', max_length=50),
        ),
    ]
